#!/usr/bin/env python3
"""Integration test for Orca Slicer support."""

from parsing.slicer_detect import detectSlicer
from parsing.router import extractParsedValues
from parsing.gcode_view import GCodeView


# Sample Orca Slicer header
ORCA_SAMPLE = """
; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2025-12-08 at 07:47:18
; model printing time: 5h 54m 40s; total estimated time: 6h 0m 41s
; estimated first layer printing time (normal mode) = 6m 0s
; total layer number: 140
; model label id: 840
; filament_density: 1.24,1.24
; filament_diameter: 1.75,1.75
; max_z_height: 28.00
; HEADER_BLOCK_END

; CONFIG_BLOCK_START
; filament_type = PLA;PLA
; layer_height = 0.2
; nozzle_diameter = 0.4
; printer_model = Bambu Lab A1
; sparse_infill_density = 10%
; enable_support = 0
; CONFIG_BLOCK_END

; filament used [mm] = 51212.00, 4221.24
; filament used [cm3] = 123.18, 10.15
; filament used [g] = 152.74, 12.59
; filament cost = 3.05, 0.25

G28 ; home
"""


class MockGCodeView:
    def __init__(self, text):
        lines = text.split('\n')
        self.headLines = lines[:50]  # First 50 lines as header
        self.text = text
        self.containerType = '3mf'
        self.plateNumber = 1

    def iterLines(self):
        return self.text.split('\n')


def test_orca_detection():
    """Test that Orca Slicer is correctly detected."""
    gview = MockGCodeView(ORCA_SAMPLE)
    guess = detectSlicer(gview)

    print("=== Orca Slicer Detection Test ===")
    print(f"Detected: {guess.name}")
    print(f"Confidence: {guess.confidence}")
    print(f"Hints: {guess.hints}")

    assert guess.name == 'orca', f"Expected 'orca', got '{guess.name}'"
    assert guess.confidence == 1.0, f"Expected confidence 1.0, got {guess.confidence}"
    print("✓ Detection test passed\n")

    return guess


def test_orca_extraction():
    """Test that values are correctly extracted from Orca files."""
    gview = MockGCodeView(ORCA_SAMPLE)
    guess = detectSlicer(gview)
    parsed = extractParsedValues(gview, guess)

    print("=== Orca Slicer Extraction Test ===")
    print(f"Slicer: {parsed.meta.get('slicer')}")
    print(f"Print time (sec): {parsed.fieldValues.get('printTimeSec')}")
    print(f"Total layers: {parsed.fieldValues.get('totalLayers')}")
    print(f"Objects on plate: {parsed.fieldValues.get('objectsOnPlate')}")
    print(f"Max Z height: {parsed.fieldValues.get('maxZHeight')}")
    print(f"Filament used (g): {parsed.fieldValues.get('filamentUsedGrams')}")
    print(f"Filament weights: {parsed.fieldValues.get('filamentWeights')}")
    print(f"Filament type: {parsed.fieldValues.get('filament_type')}")
    print(f"Layer height: {parsed.fieldValues.get('layer_height')}")
    print(f"Nozzle diameter: {parsed.fieldValues.get('nozzle_diameter')}")
    print(f"Printer model: {parsed.fieldValues.get('printer_model')}")

    # Verify critical fields
    assert parsed.meta.get('slicer') == 'orca', "Wrong slicer in meta"
    assert parsed.fieldValues.get('printTimeSec') == '21280', f"Wrong print time: {parsed.fieldValues.get('printTimeSec')}"
    assert parsed.fieldValues.get('totalLayers') == '140', f"Wrong layer count: {parsed.fieldValues.get('totalLayers')}"
    assert parsed.fieldValues.get('maxZHeight') == '28.00', f"Wrong Z height: {parsed.fieldValues.get('maxZHeight')}"
    assert parsed.fieldValues.get('filamentUsedGrams') == '165.33', f"Wrong filament weight: {parsed.fieldValues.get('filamentUsedGrams')}"
    assert parsed.fieldValues.get('filamentCost') == '3.30', f"Wrong filament cost: {parsed.fieldValues.get('filamentCost')}"

    print("✓ Extraction test passed\n")

    return parsed


if __name__ == '__main__':
    print("Testing Orca Slicer integration...\n")

    try:
        test_orca_detection()
        test_orca_extraction()
        print("=" * 50)
        print("✓ ALL TESTS PASSED!")
        print("=" * 50)
    except AssertionError as e:
        print(f"\n✗ TEST FAILED: {e}")
        exit(1)
    except Exception as e:
        print(f"\n✗ ERROR: {e}")
        import traceback
        traceback.print_exc()
        exit(1)
