#!/usr/bin/env python3
"""Integration test for Klipper/Snapmaker U1 G-code support with toolchanger."""

from parsing.slicer_detect import detectSlicer
from parsing.router import extractParsedValues
from parsing.gcode_view import GCodeView


# Sample Klipper G-code from Snapmaker U1 (toolchanger)
KLIPPER_SAMPLE = """; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2026-01-11 at 23:43:26
; total layer number: 126
; filament_density: 1.25,1.25,1.25,1.25
; filament_diameter: 1.75,1.75,1.75,1.75
; max_z_height: 25.45
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 48x48 924
; iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAACeklEQVR4Ae2Y2W3yQBSFBxD7vu/7vs
; MD75SQElwCHVACJVCCS6AESnAJLmH+c6w4QlESYf5Enof5pCvHSQbdM3ebQQiNRqPRaDQazUvkcjkj
; k8m8iRfheuEXwWAwt1gsZLvdviWTySPfhUeGw+E9kUi8vAH/RaVSuVAAbblcymg0enxmHYV2Oh1ztV
; rZ6/VaVqtVU/hBvV6/wglJG41GMhwO755di523t9utpIBGo3EXftBsNrmLjhNwSHpJIUTgvtlsnOhB
; gCX8ABEw6QAdQR1cvawtlUonCmfk8Dn+CEAHOU8mE/meRvaz3Sgej+8g3J7NZrLb7cpisehPDbB79P
; t9SREs4v1+byM1znTwq/8PhUI5OOvsPNdwLSInU6nUSfgFC5COMBXm87mTTofDwRGDd/7NRH3cptOp
; RZF4OvXS6/Vkq9Vi/tvCT9g6seuOQxRC57i7TA/X6DR/R5Gu42gAjiGKhvAbpgBFMJ/5dH+ms3zSXK
; ex4x/OI51uQhUYCQwki44yr10hNL6/p8uHYXL7l/ffwTkQi8XeuLOY0hbaI1ukrNVqjuXzeVNJx7+D
; ggKBgOfzkUbzAKazMR6PbZiFrnRDoZ8jkUhPqA6nbqFQMNB9bo9diXOCgsrlsprFzGMED3Y8Kj8aJ7
; Q7iQeDgTPY0JUMoRIYaMfPjn9lFEMhmNIWIyVUgI484/zniLAmhApgul68CHBvY17vEX8GOozpVQAj
; gIuNGgJwZPAcAV6EUMhqpBDOQDvmtdc64DqhCjiwXbyISKfT/nwf9BPZbNbATcz+yXG2UMyLo1AZHC
; FOiMgVt7Q7pi+PEXdM3zOO04bQaDQajeYX+Qf6nWXk14okSAAAAABJRU5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm

; EXECUTABLE_BLOCK_START
M73 P0 R43
M106 S0
;TYPE:Custom
;===== machine: PR2 ========================
PRINT_START
T0
M109 S220 T0
M106 S0

TIMELAPSE_START
G90
G21
M83 ; use relative distances for extrusion
; Filament gcode
T0
M106 S0
;LAYER_CHANGE
;Z:0.25
;HEIGHT:0.25

G1 X125.206 Y158.894 F30000
G1 Z.65
G1 Z.25
; some more gcode...
; EXECUTABLE_BLOCK_END

; filament used [mm] = 7252.86, 0.00, 0.00, 0.00
; filament used [cm3] = 17.45, 0.00, 0.00, 0.00
; filament used [g] = 21.81, 0.00, 0.00, 0.00
; filament cost = 0.50, 0.00, 0.00, 0.00
; total filament used [g] = 21.81
; total filament cost = 0.50
; total layers count = 127
; estimated printing time (normal mode) = 43m 45s

; CONFIG_BLOCK_START
; gcode_flavor = klipper
; printer_model = Snapmaker U1
; extruder_colour = #000000;#400080;#FF0000;#000000
; filament_type = PLA;PLA;PLA;PLA
; nozzle_diameter = 0.4,0.4,0.4,0.4
; layer_height = 0.2
; hot_plate_temp = 55,55,55,55
; nozzle_temperature = 220,220,220,220
; CONFIG_BLOCK_END
"""


class MockGCodeView:
    def __init__(self, text):
        lines = text.split('\n')
        self.headLines = lines[:100]  # First 100 lines as header
        self.text = text
        self.containerType = 'gcode'
        self.plateNumber = 1

    def iterLines(self):
        return self.text.split('\n')


def test_klipper_detection():
    """Test that Klipper G-code from OrcaSlicer is correctly detected."""
    gview = MockGCodeView(KLIPPER_SAMPLE)
    guess = detectSlicer(gview)

    print("=== Klipper/Snapmaker Detection Test ===")
    print(f"Detected: {guess.name}")
    print(f"Confidence: {guess.confidence}")
    print(f"Hints: {guess.hints}")

    assert guess.name == 'orca', f"Expected 'orca', got '{guess.name}'"
    assert guess.confidence == 1.0, f"Expected confidence 1.0, got {guess.confidence}"
    print("✓ Detection test passed\n")

    return guess


def test_klipper_extraction():
    """Test that values are correctly extracted from Klipper/Snapmaker G-code."""
    gview = MockGCodeView(KLIPPER_SAMPLE)
    guess = detectSlicer(gview)
    parsed = extractParsedValues(gview, guess)

    print("=== Klipper/Snapmaker Extraction Test ===")
    print(f"Slicer: {parsed.meta.get('slicer')}")
    print(f"Is Klipper: {parsed.meta.get('isKlipper')}")
    print(f"Print time (sec): {parsed.fieldValues.get('printTimeSec')}")
    print(f"Total layers: {parsed.fieldValues.get('totalLayers')}")
    print(f"Max Z height: {parsed.fieldValues.get('maxZHeight')}")
    print(f"Filament used (g): {parsed.fieldValues.get('filamentUsedGrams')}")
    print(f"Filament weights: {parsed.fieldValues.get('filamentWeights')}")
    print(f"Filament cost: {parsed.fieldValues.get('filamentCost')}")
    print(f"G-code flavor: {parsed.fieldValues.get('gcode_flavor')}")
    print(f"Printer model: {parsed.fieldValues.get('printer_model')}")
    print(f"Extruder count: {parsed.fieldValues.get('extruderCount')}")
    print(f"Extruder colors: {parsed.fieldValues.get('extruderColors')}")
    print(f"Tools used: {parsed.fieldValues.get('toolsUsed')}")
    print(f"Bed temperature: {parsed.fieldValues.get('buildPlateTemperature')}")
    print(f"Nozzle temperature: {parsed.fieldValues.get('hotendTemperature')}")
    print(f"Thumbnails: {len(parsed.fieldValues.get('thumbnails', []))} found")

    # Verify critical fields
    assert parsed.meta.get('slicer') == 'orca', "Wrong slicer in meta"
    assert parsed.meta.get('isKlipper') == True, "Should detect Klipper"

    # Print time: 43m 45s = 43*60 + 45 = 2625 seconds
    assert parsed.fieldValues.get('printTimeSec') == '2625', f"Wrong print time: {parsed.fieldValues.get('printTimeSec')}"

    # Total layers (should use 'total layers count' fallback)
    assert parsed.fieldValues.get('totalLayers') in ('126', '127'), f"Wrong layer count: {parsed.fieldValues.get('totalLayers')}"

    # Max Z height
    assert parsed.fieldValues.get('maxZHeight') == '25.45', f"Wrong Z height: {parsed.fieldValues.get('maxZHeight')}"

    # Filament weight
    assert parsed.fieldValues.get('filamentUsedGrams') == '21.81', f"Wrong filament weight: {parsed.fieldValues.get('filamentUsedGrams')}"

    # Filament cost
    assert parsed.fieldValues.get('filamentCost') == '0.50', f"Wrong filament cost: {parsed.fieldValues.get('filamentCost')}"

    # G-code flavor should be klipper
    assert parsed.fieldValues.get('gcode_flavor') == 'klipper', f"Wrong gcode_flavor: {parsed.fieldValues.get('gcode_flavor')}"

    # Printer model
    assert parsed.fieldValues.get('printer_model') == 'Snapmaker U1', f"Wrong printer model: {parsed.fieldValues.get('printer_model')}"

    # Extruder count (4 extruders for toolchanger)
    assert parsed.fieldValues.get('extruderCount') == '4', f"Wrong extruder count: {parsed.fieldValues.get('extruderCount')}"

    # Thumbnails should be extracted
    thumbnails = parsed.fieldValues.get('thumbnails', [])
    assert len(thumbnails) >= 1, f"Expected at least 1 thumbnail, got {len(thumbnails)}"

    # Check thumbnail dimensions
    thumb48 = next((t for t in thumbnails if t.get('width') == 48), None)
    assert thumb48 is not None, "Expected 48x48 thumbnail"
    assert thumb48.get('height') == 48, "Wrong thumbnail height"
    assert thumb48.get('format') == 'png', "Expected PNG format"

    print("✓ Extraction test passed\n")

    return parsed


def test_thumbnail_extraction():
    """Test that thumbnails are correctly extracted from G-code."""
    gview = MockGCodeView(KLIPPER_SAMPLE)
    guess = detectSlicer(gview)
    parsed = extractParsedValues(gview, guess)

    print("=== Thumbnail Extraction Test ===")
    thumbnails = parsed.fieldValues.get('thumbnails', [])
    print(f"Found {len(thumbnails)} thumbnail(s)")

    for i, thumb in enumerate(thumbnails):
        print(f"  Thumbnail {i + 1}:")
        print(f"    Size: {thumb.get('width')}x{thumb.get('height')}")
        print(f"    Format: {thumb.get('format')}")
        print(f"    Data length: {len(thumb.get('data', ''))} chars")
        if thumb.get('valid') == False:
            print(f"    Valid: False (decode failed)")

    # Verify plateImageBase64 is set
    plateImage = parsed.fieldValues.get('plateImageBase64')
    assert plateImage is not None, "plateImageBase64 should be set"
    print(f"  plateImageBase64 set: Yes ({len(plateImage)} chars)")

    print("✓ Thumbnail test passed\n")


if __name__ == '__main__':
    print("Testing Klipper/Snapmaker U1 G-code integration...\n")

    try:
        test_klipper_detection()
        test_klipper_extraction()
        test_thumbnail_extraction()
        print("=" * 50)
        print("✓ ALL TESTS PASSED!")
        print("=" * 50)
    except AssertionError as e:
        print(f"\n✗ TEST FAILED: {e}")
        exit(1)
    except Exception as e:
        print(f"\n✗ ERROR: {e}")
        import traceback
        traceback.print_exc()
        exit(1)
