import sys
import os

# Add parent directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '.')))

from plate_scanner import analyze_gcode_quick, QuickAnalysis

def test_bambu_quick_analysis():
    print("Testing Bambu style quick analysis...")
    gcode = """
; HEADER_BLOCK_START
; BambuStudio 02.02.01.60
; model printing time: 19h 23m 23s; total estimated time: 19h 29m 38s
; total layer number: 325
; total filament length [mm] : 31379.69,116547.43
; total filament volume [cm^3] : 75477.00,280329.43
; total filament weight [g] : 95.10,353.22
; filament_density: 1.26,1.26
; filament_diameter: 1.75,1.75
; filament_type: PLA,PETG
; HEADER_BLOCK_END
"""
    result = analyze_gcode_quick(gcode.encode('utf-8'))
    
    print(f"Result: {result}")
    
    assert result.printTimeSeconds == 19*3600 + 23*60 + 23
    assert result.estimatedPrintTime == "19h 23m 23s"
    assert "448.32g" in result.filamentWeight # 95.10 + 353.22
    assert "147.93m" in result.filamentLength # (31379.69 + 116547.43) / 1000
    assert result.material == "PETG/PLA" or result.material == "PLA/PETG"
    assert result.layerCount == 325
    print("Bambu quick test passed!")

def test_prusa_quick_analysis():
    print("\nTesting Prusa style quick analysis...")
    gcode = """
; exploded by EasyPrint v1.0.0
; generated by PrusaSlicer 2.7.1
; estimated printing time (normal mode) = 2h 30m 45s
; filament used [mm] = 51212.00
; filament used [g] = 152.74
; total layers count = 127
; filament_type = PLA
"""
    result = analyze_gcode_quick(gcode.encode('utf-8'))
    
    print(f"Result: {result}")
    
    assert result.printTimeSeconds == 2*3600 + 30*60 + 45
    assert result.estimatedPrintTime == "2h 30m 45s"
    assert result.filamentWeight == "152.74g"
    assert result.filamentLength == "51.21m"
    assert result.material == "PLA"
    assert result.layerCount == 127
    print("Prusa quick test passed!")

if __name__ == "__main__":
    try:
        test_bambu_quick_analysis()
        test_prusa_quick_analysis()
        print("\nAll quick analysis tests passed!")
    except Exception as e:
        print(f"\nTest failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
