import os
import sys

sys.path.append(os.getcwd())

from parsing.slicer_detect import detectSlicer
from parsing.router import extractParsedValues
from parsing.gcode_view import GCodeView

# Create a mock view that mimics a standard Orca file (no toolchanger)
mock_lines = [
    "; generated by OrcaSlicer",
    "; printer_model = Generic Printer",
    "; filament used [g] = 10.5, 20.0",
    "; filament used [mm] = 123.4, 456.7",
    "; filament used [cm3] = 10.0, 19.0",
]
head_lines = mock_lines

gview = GCodeView(
    lines=mock_lines,
    headLines=head_lines,
    attachments={},
    containerType='gcode',
    fileName='test.gcode',
    plateNumber=1
)

def test_standard_parsing():
    print("Testing Standard Orca Parsing...")
    guess = detectSlicer(gview)
    print(f"Detected: {guess.name}")
    
    result = extractParsedValues(gview, guess)
    analysis = result.fieldValues.get('filamentAnalysis', [])
    
    print("\n[+] Filament Analysis:")
    for item in analysis:
        # Check if toolIndex exists
        t_idx = item.get('toolIndex', 'MISSING')
        print(f"  Weight: {item.get('weightG')}, ToolIndex: {t_idx}")

if __name__ == "__main__":
    test_standard_parsing()
