from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Iterable

from .gcode_view import GCodeView


@dataclass
class SlicerGuess:
    name: str
    confidence: float
    hints: Dict[str, Any]


BAMBU_MARKERS = (
    'generated by bambu studio',
    ';slicer:bambu',
    '; bambu studio',
    'flush_start',
    'flush_end',
    'bambu lab',
)


def detectSlicer(gview: GCodeView) -> SlicerGuess:
    lowerHead = [line.lower() for line in gview.headLines]
    hits = [marker for marker in BAMBU_MARKERS if any(marker in line for line in lowerHead)]
    if hits:
        return SlicerGuess(name='bambu', confidence=1.0, hints={'markers': hits})
    return SlicerGuess(name='unknown', confidence=0.0, hints={})
