from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Dict

from .gcode_view import GCodeView


@dataclass
class SlicerGuess:
    name: str
    confidence: float
    hints: Dict[str, Any]


BAMBU_MARKERS = (
    'generated by bambu studio',
    ';slicer:bambu',
    '; bambu studio',
    'flush_start',
    'flush_end',
    'bambu lab',
)

ORCA_MARKERS = (
    'generated by orcaslicer',
    'orca slicer',
    'orcaslicer',
)


def detectSlicer(gview: GCodeView) -> SlicerGuess:
    lowerHead = [line.lower() for line in gview.headLines]

    # Check for Snapmaker markers first (as it might also have Orca/Bambu markers)
    # Snapmaker U1 puts config at the end of the file, so check tail as well
    tailLines = [line.lower() for line in gview.lines[-1000:]]
    checkLines = lowerHead + tailLines

    snapmakerHits = [
        'printer_model = snapmaker', 
        'printer_model = j1', 
        'printer_model = u1'
    ]
    if any(m in line for line in checkLines for m in snapmakerHits):
        return SlicerGuess(name='snapmaker', confidence=1.0, hints={'markers': ['snapmaker']})

    # Check for Orca Slicer first (since it's a fork of Bambu Studio)
    orcaHits = [marker for marker in ORCA_MARKERS if any(marker in line for line in lowerHead)]
    if orcaHits:
        return SlicerGuess(name='orca', confidence=1.0, hints={'markers': orcaHits})

    # Check for Bambu Studio
    bambuHits = [marker for marker in BAMBU_MARKERS if any(marker in line for line in lowerHead)]
    if bambuHits:
        return SlicerGuess(name='bambu', confidence=1.0, hints={'markers': bambuHits})

    # Check for EasyPrint/PrusaSlicer
    easyPrintGuess = detectEasyPrint(gview)
    if easyPrintGuess is not None:
        return easyPrintGuess

    return SlicerGuess(name='unknown', confidence=0.0, hints={})


def detectEasyPrint(gview: GCodeView) -> SlicerGuess | None:
    headText = '\n'.join(gview.headLines)
    score = 0.0
    hints: Dict[str, Any] = {}

    if re.search(r";\s*prepared by EasyPrint\s+v[\d.]+", headText, re.IGNORECASE):
        score += 4
        hints['prep'] = 'easyprint'
    if re.search(r";\s*generated by PrusaSlicer", headText, re.IGNORECASE):
        score += 3
        hints['gen'] = 'prusaslicer'
    if re.search(r";\s*estimated printing time", headText, re.IGNORECASE):
        score += 1
    if re.search(r";\s*total layers count\s*=", headText, re.IGNORECASE):
        score += 1
    if re.search(r";\s*objects_info\s*=\s*\{", headText, re.IGNORECASE):
        score += 1
    if re.search(r"gcode_flavor\s*=\s*marlin", headText, re.IGNORECASE):
        score += 0.5
    prusaKeys = [
        r";\s*filament used \[mm\]",
        r";\s*filament used \[(?:cm3|cm\^3)\]",
        r";\s*filament used \[g\]",
        r";\s*printer_model\s*=",
        r";\s*nozzle_diameter\s*=",
        r";\s*layer_height\s*=",
    ]
    for keyPattern in prusaKeys:
        if re.search(keyPattern, headText, re.IGNORECASE):
            score += 0.5

    if score >= 4:
        confidence = min(1.0, 0.6 + 0.1 * score)
        return SlicerGuess(name='easyprint', confidence=confidence, hints=hints)
    return None
