from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Dict

from .gcode_view import GCodeView


"""Slicer Detection Module

This module provides functionality to identify which slicing software was used to generate
3D printer G-code files. Accurate slicer detection is critical because different slicers
use different comment formats, metadata structures, and conventions for embedding information
in G-code files.

Supported Slicers:
    - Bambu Studio: Official slicer for Bambu Lab 3D printers
    - Orca Slicer: Fork of Bambu Studio with additional features
    - EasyPrint/PrusaSlicer: Prusa Research slicer and its derivatives

Detection Strategy:
    The detection process uses a multi-stage approach with fallback mechanisms:

    1. Check for Orca Slicer markers first (because it's a Bambu Studio fork and may
       contain both Orca and Bambu markers)
    2. Check for Bambu Studio markers
    3. Check for EasyPrint/PrusaSlicer using a confidence-scoring algorithm
    4. Fall back to 'unknown' if no slicer can be identified

    Detection is based on analyzing the header section of G-code files, which typically
    contains metadata comments generated by the slicing software.

Confidence Scores:
    - 1.0: Definitive match based on explicit slicer markers
    - 0.6-1.0: High confidence based on multiple characteristic patterns (EasyPrint)
    - 0.0: No slicer could be identified

Example:
    >>> from parsing.gcode_view import GCodeView
    >>> gview = GCodeView(headLines=["; generated by OrcaSlicer 1.0"], ...)
    >>> result = detectSlicer(gview)
    >>> print(f"{result.name} (confidence: {result.confidence})")
    orca (confidence: 1.0)
"""


@dataclass
class SlicerGuess:
    """Represents the result of slicer detection analysis.

    This dataclass encapsulates the outcome of attempting to identify which slicing
    software generated a G-code file. It includes not only the detected slicer name
    but also a confidence score and diagnostic hints that can be used for debugging
    or logging purposes.

    Attributes:
        name: The identified slicer name. Possible values:
            - 'bambu': Bambu Studio slicer
            - 'orca': Orca Slicer (Bambu Studio fork)
            - 'easyprint': EasyPrint or PrusaSlicer
            - 'unknown': Could not identify the slicer

        confidence: A float between 0.0 and 1.0 indicating detection confidence.
            - 1.0 = Definitive match (found explicit slicer markers)
            - 0.6-0.99 = High confidence (multiple characteristic patterns matched)
            - 0.0 = No slicer identified

        hints: A dictionary containing diagnostic information about the detection.
            The structure varies by slicer:
            - For Bambu/Orca: {'markers': [list of matched marker strings]}
            - For EasyPrint: {'prep': 'easyprint', 'gen': 'prusaslicer', ...}
            - For unknown: {} (empty dict)

            These hints are useful for debugging detection failures or understanding
            why a particular slicer was chosen.

    Example:
        >>> guess = SlicerGuess(
        ...     name='orca',
        ...     confidence=1.0,
        ...     hints={'markers': ['generated by orcaslicer']}
        ... )
        >>> print(f"Detected {guess.name} with {guess.confidence*100}% confidence")
        Detected orca with 100.0% confidence
    """
    name: str
    confidence: float
    hints: Dict[str, Any]


# Marker strings that uniquely identify Bambu Studio G-code files.
# These strings are typically found in header comments or embedded commands.
# Note: Orca Slicer (a Bambu fork) may also contain some Bambu markers,
# so Orca detection must be performed first to avoid false positives.
BAMBU_MARKERS = (
    'generated by bambu studio',  # Standard header comment
    ';slicer:bambu',              # Slicer identification metadata
    '; bambu studio',             # Alternative header format
    'flush_start',                # Bambu-specific purge tower command
    'flush_end',                  # Bambu-specific purge tower command
    'bambu lab',                  # Manufacturer reference
)

# Marker strings that uniquely identify Orca Slicer G-code files.
# Orca Slicer is a fork of Bambu Studio with additional features.
# IMPORTANT: Must check for Orca markers BEFORE Bambu markers because
# Orca files may contain both Orca and Bambu identifiers.
ORCA_MARKERS = (
    'generated by orcaslicer',  # Standard header comment
    'orca slicer',              # Alternative header format
    'orcaslicer',               # Compact identifier
)


def detectSlicer(gview: GCodeView) -> SlicerGuess:
    """Detect which slicing software generated the G-code file.

    This is the main entry point for slicer detection. It analyzes the header section
    of a G-code file to determine which slicing software was used to generate it.
    The detection uses a priority-based approach to handle cases where slicers share
    common markers (e.g., Orca Slicer being a fork of Bambu Studio).

    Detection Order (CRITICAL - do not reorder):
        1. Orca Slicer - Checked first because it's a Bambu fork and may contain
           both Orca and Bambu markers. If we checked Bambu first, we'd get false
           positives for Orca files.
        2. Bambu Studio - Checked second after ruling out Orca
        3. EasyPrint/PrusaSlicer - Uses a confidence-based scoring algorithm
        4. Unknown - Fallback when no slicer can be identified

    The function performs case-insensitive matching to handle variations in
    capitalization across different slicer versions.

    Args:
        gview: A GCodeView object containing the parsed G-code file, including
            the header lines which typically contain slicer metadata and comments.

    Returns:
        A SlicerGuess object containing:
            - name: The detected slicer ('orca', 'bambu', 'easyprint', or 'unknown')
            - confidence: Detection confidence (1.0 for marker-based, 0.6-1.0 for
              pattern-based, 0.0 for unknown)
            - hints: Diagnostic information about which markers/patterns matched

    Example:
        >>> from parsing.gcode_view import GCodeView
        >>> gview = GCodeView(
        ...     headLines=[
        ...         "; generated by OrcaSlicer 1.9.0",
        ...         "; total layers = 150"
        ...     ],
        ...     containerType='gcode'
        ... )
        >>> result = detectSlicer(gview)
        >>> print(result.name)
        orca
        >>> print(result.confidence)
        1.0
        >>> print(result.hints)
        {'markers': ['generated by orcaslicer']}

    Note:
        This function only examines the header section (gview.headLines), not the
        entire G-code file. The header typically contains all necessary metadata
        for slicer identification, and this approach is much more efficient than
        scanning the entire file.
    """
    lowerHead = [line.lower() for line in gview.headLines]

    # Check for Orca Slicer first (since it's a fork of Bambu Studio)
    orcaHits = [marker for marker in ORCA_MARKERS if any(marker in line for line in lowerHead)]
    if orcaHits:
        return SlicerGuess(name='orca', confidence=1.0, hints={'markers': orcaHits})

    # Check for Bambu Studio
    bambuHits = [marker for marker in BAMBU_MARKERS if any(marker in line for line in lowerHead)]
    if bambuHits:
        return SlicerGuess(name='bambu', confidence=1.0, hints={'markers': bambuHits})

    # Check for EasyPrint/PrusaSlicer
    easyPrintGuess = detectEasyPrint(gview)
    if easyPrintGuess is not None:
        return easyPrintGuess

    return SlicerGuess(name='unknown', confidence=0.0, hints={})


def detectEasyPrint(gview: GCodeView) -> SlicerGuess | None:
    """Detect EasyPrint or PrusaSlicer using confidence-based pattern scoring.

    This function uses a sophisticated scoring algorithm to identify EasyPrint and
    PrusaSlicer-generated G-code files. Unlike Bambu/Orca detection which relies on
    explicit markers, this approach accumulates evidence from multiple characteristic
    patterns because EasyPrint and PrusaSlicer don't always include definitive
    identification strings.

    Scoring System:
        High-value indicators (definitive identification):
            - "prepared by EasyPrint vX.X.X" → +4.0 points
            - "generated by PrusaSlicer" → +3.0 points

        Medium-value indicators (strong evidence):
            - "estimated printing time" → +1.0 point
            - "total layers count =" → +1.0 point
            - "objects_info = {" → +1.0 point
            - "gcode_flavor = marlin" → +0.5 points

        Low-value indicators (supporting evidence, each → +0.5 points):
            - "filament used [mm]"
            - "filament used [cm3]" or "filament used [cm^3]"
            - "filament used [g]"
            - "printer_model ="
            - "nozzle_diameter ="
            - "layer_height ="

        Threshold: Score must be ≥ 4.0 to return a positive detection
        Confidence: Calculated as min(1.0, 0.6 + 0.1 * score)
            - Score 4.0 → 1.0 confidence (capped at 1.0)
            - Score 5.0 → 1.0 confidence
            - Higher scores increase confidence up to 1.0

    Why This Approach:
        EasyPrint is based on PrusaSlicer and shares many metadata patterns with it.
        Rather than looking for a single definitive marker, this function looks for
        a combination of patterns that collectively indicate EasyPrint/PrusaSlicer
        origin. This makes detection more robust against variations in slicer
        configurations and versions.

    Args:
        gview: A GCodeView object containing the parsed G-code file with header lines.

    Returns:
        SlicerGuess | None:
            - Returns a SlicerGuess with name='easyprint', confidence 0.6-1.0, and
              hints containing matched patterns if score ≥ 4.0
            - Returns None if score < 4.0 (insufficient evidence)

    Example:
        >>> from parsing.gcode_view import GCodeView
        >>> gview = GCodeView(
        ...     headLines=[
        ...         "; prepared by EasyPrint v2.5.1",
        ...         "; estimated printing time = 2h 30m",
        ...         "; filament used [g] = 25.4",
        ...         "; nozzle_diameter = 0.4"
        ...     ],
        ...     containerType='gcode'
        ... )
        >>> result = detectEasyPrint(gview)
        >>> print(result.name if result else "Not detected")
        easyprint
        >>> print(result.confidence if result else "N/A")
        1.0

    Note:
        This function is called by detectSlicer() only after ruling out Orca and
        Bambu slicers. It serves as a fallback detection mechanism for PrusaSlicer-
        family slicers.
    """
    headText = '\n'.join(gview.headLines)
    score = 0.0
    hints: Dict[str, Any] = {}

    # High-value indicators - strong evidence of EasyPrint/PrusaSlicer
    if re.search(r";\s*prepared by EasyPrint\s+v[\d.]+", headText, re.IGNORECASE):
        score += 4
        hints['prep'] = 'easyprint'
    if re.search(r";\s*generated by PrusaSlicer", headText, re.IGNORECASE):
        score += 3
        hints['gen'] = 'prusaslicer'

    # Medium-value indicators - characteristic patterns
    if re.search(r";\s*estimated printing time", headText, re.IGNORECASE):
        score += 1
    if re.search(r";\s*total layers count\s*=", headText, re.IGNORECASE):
        score += 1
    if re.search(r";\s*objects_info\s*=\s*\{", headText, re.IGNORECASE):
        score += 1
    if re.search(r"gcode_flavor\s*=\s*marlin", headText, re.IGNORECASE):
        score += 0.5

    # Low-value indicators - common PrusaSlicer metadata fields
    prusaKeys = [
        r";\s*filament used \[mm\]",
        r";\s*filament used \[(?:cm3|cm\^3)\]",
        r";\s*filament used \[g\]",
        r";\s*printer_model\s*=",
        r";\s*nozzle_diameter\s*=",
        r";\s*layer_height\s*=",
    ]
    for keyPattern in prusaKeys:
        if re.search(keyPattern, headText, re.IGNORECASE):
            score += 0.5

    # Return positive detection if score meets threshold
    if score >= 4:
        confidence = min(1.0, 0.6 + 0.1 * score)
        return SlicerGuess(name='easyprint', confidence=confidence, hints=hints)
    return None
