from __future__ import annotations

import json
import re
from typing import Any, Dict, List, Optional

from .base import (
    ParsedValues,
    deriveWeightGFromLength,
    parseDurationToSeconds,
    toFloat,
)
from ..gcode_view import GCodeView


RE_ESTIMATED_TIME = re.compile(r";\s*estimated printing time.*=\s*(?P<value>[\dhms :]+)", re.IGNORECASE)
RE_FILAMENT_MM = re.compile(r";\s*filament used \[mm\]\s*=\s*(?P<value>[\d.,]+)", re.IGNORECASE)
RE_FILAMENT_CM3 = re.compile(r";\s*filament used \[(?:cm3|cm\^3)\]\s*=\s*(?P<value>[\d.,]+)", re.IGNORECASE)
RE_FILAMENT_G = re.compile(r";\s*(?:total\s+)?filament used \[g\]\s*=\s*(?P<value>[\d.,]+)", re.IGNORECASE)
RE_TOTAL_LAYERS = re.compile(r";\s*total layers count\s*=\s*(?P<value>\d+)", re.IGNORECASE)
RE_OBJECTS_INFO = re.compile(r";\s*objects_info\s*=\s*(?P<value>\{.*\})", re.IGNORECASE)
RE_Z_MOVE = re.compile(r"[GM]0?1[^;]*\bZ(?P<value>[\d.]+)", re.IGNORECASE)
RE_M486 = re.compile(r"^\s*M486\s+A(?P<name>.*)$", re.IGNORECASE)
RE_LAYER_MARKER = re.compile(r";\s*LAYER\s*:?\s*(?P<index>\d+)", re.IGNORECASE)


def matchConfigValue(pattern: re.Pattern[str], line: str) -> Optional[str]:
    strippedLine = line.lstrip(';').strip()
    match = pattern.match(strippedLine)
    if match:
        return match.group('value').strip()
    return None


class EasyPrintGcodeExtractor:
    def extract(self, gview: GCodeView) -> ParsedValues:
        headText = '\n'.join(gview.headLines)
        fieldValues: Dict[str, Any] = {
            'objects': [],
            'orderedObjects': [],
            'filamentAnalysis': [],
            'filamentWeights': [],
        }
        meta: Dict[str, Any] = {
            'slicerName': 'easyprint',
            'slicerBase': 'prusaslicer',
        }

        if match := re.search(r";\s*prepared by EasyPrint\s+v(?P<version>[\d.]+)", headText, re.IGNORECASE):
            meta['preparedBy'] = f"EasyPrint v{match.group('version')}"
        if match := re.search(r";\s*generated by PrusaSlicer\s*(?P<version>[^\r\n]*)", headText, re.IGNORECASE):
            meta['generatedBy'] = match.group('version').strip()

        printTimeSeconds = None
        if match := RE_ESTIMATED_TIME.search(headText):
            printTimeSeconds = parseDurationToSeconds(match.group('value'))

        filamentLengthMm = toFloat(extractFirstMatch(RE_FILAMENT_MM, headText))
        filamentVolumeCm3 = toFloat(extractFirstMatch(RE_FILAMENT_CM3, headText))
        filamentWeightG = toFloat(extractFirstMatch(RE_FILAMENT_G, headText))

        totalLayers: Optional[int] = None
        maxLayerIndex: Optional[int] = None
        maxZHeight: Optional[float] = None
        printerModel: Optional[str] = None
        printerModelFallback: Optional[str] = None
        nozzleDiameter: Optional[float] = None
        layerHeight: Optional[float] = None
        filamentDiameter: Optional[float] = None
        filamentDensity: Optional[float] = None
        filamentType: Optional[str] = None
        filamentColour: Optional[str] = None
        gcodeFlavor: Optional[str] = None
        objectsOnPlate: Optional[int] = None
        timeSegments: List[float] = []
        m486Counter = 0

        printerModelPattern = re.compile(r"^printer_model\s*=\s*(?P<value>.+)$", re.IGNORECASE)
        printerSettingsPattern = re.compile(r"^printer_settings_id\s*=\s*(?P<value>.+)$", re.IGNORECASE)
        nozzlePattern = re.compile(r"^nozzle_diameter\s*=\s*(?P<value>[\d.,]+)$", re.IGNORECASE)
        layerHeightPattern = re.compile(r"^layer_height\s*=\s*(?P<value>[\d.,]+)$", re.IGNORECASE)
        filamentDiameterPattern = re.compile(r"^filament_diameter\s*=\s*(?P<value>[\d.,]+)$", re.IGNORECASE)
        filamentDensityPattern = re.compile(r"^filament_density\s*=\s*(?P<value>[\d.,]+)$", re.IGNORECASE)
        filamentTypePattern = re.compile(r"^filament_type\s*=\s*(?P<value>\w+)$", re.IGNORECASE)
        filamentColourPattern = re.compile(r"^filament_colour\s*=\s*(?P<value>#[0-9A-Fa-f]{6})$", re.IGNORECASE)
        gcodeFlavorPattern = re.compile(r"^gcode_flavor\s*=\s*(?P<value>.+)$", re.IGNORECASE)

        for line in gview.iterLines():
            if totalLayers is None:
                totalLayersValue = matchConfigValue(RE_TOTAL_LAYERS, line)
                if totalLayersValue is not None:
                    totalLayers = int(totalLayersValue)

            if printerModel is None:
                if value := matchConfigValue(printerModelPattern, line):
                    printerModel = value
            if printerModelFallback is None:
                if value := matchConfigValue(printerSettingsPattern, line):
                    printerModelFallback = value.split('(')[0].strip()

            if value := matchConfigValue(nozzlePattern, line):
                parsedValue = toFloat(value)
                if parsedValue is not None:
                    nozzleDiameter = parsedValue

            if value := matchConfigValue(layerHeightPattern, line):
                parsedValue = toFloat(value)
                if parsedValue is not None:
                    layerHeight = parsedValue

            if value := matchConfigValue(filamentDiameterPattern, line):
                parsedValue = toFloat(value)
                if parsedValue is not None:
                    filamentDiameter = parsedValue

            if value := matchConfigValue(filamentDensityPattern, line):
                parsedValue = toFloat(value)
                if parsedValue is not None:
                    filamentDensity = parsedValue

            if value := matchConfigValue(filamentTypePattern, line):
                filamentType = value

            if value := matchConfigValue(filamentColourPattern, line):
                filamentColour = value

            if gcodeFlavor is None:
                if value := matchConfigValue(gcodeFlavorPattern, line):
                    gcodeFlavor = value

            if objectsOnPlate is None:
                objectsInfoValue = matchConfigValue(RE_OBJECTS_INFO, line)
                if objectsInfoValue is not None:
                    try:
                        parsedObjects = json.loads(objectsInfoValue)
                        objectsList = parsedObjects.get('objects') or parsedObjects.get('list') or []
                        objectsOnPlate = len(objectsList)
                        meta['objectsInfo'] = parsedObjects
                    except json.JSONDecodeError:
                        pass

            if RE_M486.match(line):
                m486Counter += 1

            if match := RE_Z_MOVE.search(line):
                zValue = toFloat(match.group('value'))
                if zValue is not None:
                    if maxZHeight is None or zValue > maxZHeight:
                        maxZHeight = zValue

            if match := RE_LAYER_MARKER.search(line):
                layerIndex = int(match.group('index'))
                if maxLayerIndex is None or layerIndex > maxLayerIndex:
                    maxLayerIndex = layerIndex

            if line.startswith(';TIME:'):
                segmentValue = toFloat(line.split(':', 1)[1])
                if segmentValue is not None:
                    timeSegments.append(segmentValue)

        if objectsOnPlate is None and m486Counter:
            objectsOnPlate = m486Counter

        if printTimeSeconds is None and timeSegments:
            printTimeSeconds = int(sum(timeSegments))

        if totalLayers is None and maxLayerIndex is not None:
            totalLayers = maxLayerIndex + 1

        if totalLayers is None and maxZHeight is not None and layerHeight not in (None, 0):
            derivedLayers = int(round(maxZHeight / layerHeight))
            if derivedLayers > 0:
                totalLayers = derivedLayers

        if printerModel is None and printerModelFallback:
            printerModel = printerModelFallback

        if filamentWeightG is None:
            filamentWeightG = deriveWeightGFromLength(filamentLengthMm, filamentDiameter, filamentDensity)

        # Handle potential multi-filament in EasyPrint/Prusa
        filamentTypes = [t.strip().strip('"') for t in (filamentType or "").split(';') if t.strip()]
        filamentColors = [c.strip().strip('"') for c in (filamentColour or "").split(';') if c.strip()]

        spool: Dict[str, Any] = {}
        if filamentLengthMm is not None:
            spool['lengthMm'] = filamentLengthMm
        if filamentVolumeCm3 is not None:
            spool['volumeCm3'] = filamentVolumeCm3

        spool['weightG'] = filamentWeightG if filamentWeightG is not None else 0.0
        spool['filamentType'] = filamentTypes[0] if filamentTypes else filamentType
        spool['filamentColor'] = filamentColors[0] if filamentColors else filamentColour
        
        if spool:
            # Determine if it's AMS or Toolchanger
            # Prusa MMU / single nozzle multi-material acts like an AMS
            if meta.get('slicerBase') == 'prusaslicer' and meta.get('nozzleDiameter'):
                 spool['amsIndex'] = 0
            else:
                 spool['toolIndex'] = 0

            fieldValues['filamentAnalysis'].append(spool)
            if filamentWeightG is not None:
                fieldValues['filamentWeights'] = [filamentWeightG]

                
        # Add tools/usedTools for parity ONLY if it's a physical toolchanger
        if 'toolIndex' in spool:
            fieldValues['tools'] = fieldValues['filamentAnalysis']
            fieldValues['usedTools'] = [a for a in fieldValues['filamentAnalysis'] if a.get('weightG', 0) > 0.01]
            fieldValues['usedToolIndices'] = [a['toolIndex'] for a in fieldValues['usedTools']]



        if filamentWeightG is not None:
            fieldValues['filamentUsedGrams'] = f"{filamentWeightG:.4f}".rstrip('0').rstrip('.')
        if printTimeSeconds is not None:
            fieldValues['printTimeSec'] = str(printTimeSeconds)
        if objectsOnPlate is not None:
            fieldValues['objectsOnPlate'] = str(objectsOnPlate)
        if totalLayers is not None:
            fieldValues['totalLayers'] = str(totalLayers)
        if maxZHeight is not None:
            fieldValues['maxZHeight'] = formatFloat(maxZHeight)

        if printerModel is not None:
            meta['printerModel'] = printerModel
        if nozzleDiameter is not None:
            meta['nozzleDiameter'] = nozzleDiameter
        if layerHeight is not None:
            meta['layerHeight'] = layerHeight
        if filamentDiameter is not None:
            meta['filamentDiameter'] = filamentDiameter
        if filamentDensity is not None:
            meta['filamentDensity'] = filamentDensity
        if filamentType is not None:
            meta['filamentType'] = filamentType
        if filamentColour is not None:
            meta['filamentColour'] = filamentColour
        if gcodeFlavor is not None:
            meta['gcodeFlavor'] = gcodeFlavor

        return ParsedValues(fieldValues=fieldValues, meta=meta)


def extractFirstMatch(pattern: re.Pattern[str], text: str) -> Optional[str]:
    match = pattern.search(text)
    if match:
        return match.group('value')
    return None


def formatFloat(value: float) -> str:
    formatted = f"{value:.5f}".rstrip('0').rstrip('.')
    return formatted if formatted else '0'
