; generated by PrusaSlicer 2.5.0+
; prepared by EasyPrint v1.2.3
; estimated printing time (normal mode) = 0h 20m 44s
; filament used [mm] = 123.45
; filament used [cm3] = 3.456
; filament used [g] = 10.5
; total layers count = 50
; objects_info = {"objects":[{"name":"Widget","id":1},{"name":"Gadget","id":2}]}
; printer_model = EasyPrint MK1
; printer_settings_id = EasyPrint MK1 (Quality)
; nozzle_diameter = 0.4
; layer_height = 0.2
; filament_type = PLA
; filament_density = 1.24
; filament_diameter = 1.75
; filament_colour = #FFAA00
; gcode_flavor = marlin
;TIME:10
;TIME:20
;TIME:30
;TIME:40
M486 AWidget
M486 AGadget
;LAYER:0
G1 X0.0 Y0.0 Z0.2 F1800
;LAYER:1
G1 X10.0 Y0.0 Z0.4 F1800
;LAYER:2
G0 X10.0 Y10.0 Z0.6 F3000
;LAYER:3
G1 X20.0 Y10.0 Z0.8 F1800
;LAYER:49
G1 X30.0 Y20.0 Z10.0 F1800
G1 X30.0 Y20.0 Z9.8 F1800 ; retract to lower Z
